# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JZLProgressHUD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JZLProgressHUD
  pod 'MBProgressHUD'

  target 'JZLProgressHUDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JZLProgressHUDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
